import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :anoma_explorer, AnomaExplorerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Note: force_ssl is configured in runtime.exs to allow runtime control.
# Set FORCE_SSL=true to enable HTTPS redirect with HSTS.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
