import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :anoma_explorer, AnomaExplorerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# SSL/HTTPS redirect is now configured via FORCE_SSL environment variable
# in config/runtime.exs. Defaults to enabled (true) for security.
# Set FORCE_SSL=false to disable HTTPS redirect (e.g., when behind a proxy
# that handles TLS termination, or for health check endpoints).

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
