import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :anoma_explorer, AnomaExplorerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force SSL/HTTPS redirect with HSTS enabled.
  # Health check paths are excluded to allow HTTP health probes from load balancers.
  # Uses MFA tuple instead of anonymous function to match compile-time and runtime.
  # Set FORCE_SSL=false env var at runtime to disable (see runtime.exs).
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    exclude: {AnomaExplorerWeb.SSL, :exclude_health_checks?, []}
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
